### ISSUE TITLE
Not compatible with Sonar 6.0

### ISSUE THREAD

**Issue by joanfon** [octo-technology/sonar-objective-c#111]
After updating to SonarQube 6.0 I get the following error:

```
INFO: Sensor Objective-C Squid Sensor
Exception in thread "main" java.lang.NoSuchMethodError: org.sonar.api.resources.File.fromIOFile(Ljava/io/File;Lorg/sonar/api/resources/Project;)Lorg/sonar/api/resources/File;
    at org.sonar.plugins.objectivec.ObjectiveCSquidSensor.saveViolations(ObjectiveCSquidSensor.java:146)
    at org.sonar.plugins.objectivec.ObjectiveCSquidSensor.save(ObjectiveCSquidSensor.java:118)
    at org.sonar.plugins.objectivec.ObjectiveCSquidSensor.analyse(ObjectiveCSquidSensor.java:97)
    at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
    at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
    at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
    at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
    at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
    at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
    at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
    at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

The projects using **other** plugins are working without problems, only the projects using sonar-objective-c plugin are throwing that error.

**Comment by richlewis14** [comment]
Hi, getting the same issue when using SonarQube 6.0

**Comment by TYRONEMICHAEL** [comment]
+ 1

**Comment by TYRONEMICHAEL** [comment]
Same issue here +1

**Comment by jofremm** [comment]
I'm getting the same exception with sonar-objective-c-plugin-0.5.0-SNAPSHOT.jar

**Comment by martinduris** [comment]
Hi,
is there anything new with this error ? Can i help somehow ? :-)

**Comment by ghost** [comment]
Same issue here :-(

**Comment by uditsalwan** [comment]
Same exception with sonar-objective-c-plugin-0.5.0-SNAPSHOT.jar.

**Comment by AriX** [comment]
This fork has Sonar 6 support in progress: https://github.com/Backelite/sonar-objective-c
