### ISSUE TITLE
The rule 'OCLint:feature envy' does not exist.

### ISSUE THREAD

**Issue by rajasekaran2015** [octo-technology/sonar-objective-c#57]
Please help me to resolve this issue.
I am facing error while running the "sonar-runner" cmd. 
I am using Xcode 5.1 with iOS 7., OCLint version 0.9dev.

look like we have to update the profile-oclint.xml & rules.txt with the latest rules available in oclint.
Please let me know, how to update or generate the all the rules in profile-oclint.xml?

please find the below console log.
Rajasekaran-MacBook-Pro-4:SampleiOSProject arunsanthanam$ sonar-runner
SonarQube Runner 2.3
Java 1.6.0_65 Apple Inc. (64-bit)
Mac OS X 10.8.5 x86_64
INFO: Runner configuration file: /Users/arunsanthanam/TeamCityIntegrationTools/sonar-runner-2.3/conf/sonar-runner.properties
INFO: Project configuration file: /Users/arunsanthanam/buildAgent/work/92fa1b91071cafc3/SampleiOSProject/sonar-project.properties
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Work directory: /Users/arunsanthanam/buildAgent/work/92fa1b91071cafc3/SampleiOSProject/.sonar
INFO: SonarQube Server 4.2
21:53:01.989 INFO - Load batch settings
21:53:02.260 INFO - User cache: /Users/arunsanthanam/.sonar/cache
21:53:02.273 INFO - Install plugins
21:53:03.060 INFO - Install JDBC driver
21:53:03.114 INFO - Create JDBC datasource for jdbc:mysql://10.137.181.117:3306/sonar?useUnicode=true&characterEncoding=utf8
21:53:06.445 INFO - Initializing Hibernate
21:53:14.405 INFO - Load project settings
21:53:14.525 INFO - Apply project exclusions
21:53:15.249 INFO - ------------- Scan SampleiOSProject
21:53:15.254 INFO - Load module settings
21:53:20.025 INFO - Language is forced to objc
21:53:20.065 INFO - Loading technical debt model...
21:53:21.313 INFO - Loading technical debt model done: 1248 ms
21:53:21.340 INFO - Configure Maven plugins
21:53:21.818 INFO - Compare to previous analysis (2014-04-22)
21:53:21.895 INFO - Compare over 30 days (2014-03-23, analysis of 2014-04-09 20:03:13.0)
21:53:22.326 INFO - Base dir: /Users/arunsanthanam/buildAgent/work/92fa1b91071cafc3/SampleiOSProject
21:53:22.326 INFO - Working dir: /Users/arunsanthanam/buildAgent/work/92fa1b91071cafc3/SampleiOSProject/.sonar
21:53:22.326 INFO - Source dirs: /Users/arunsanthanam/buildAgent/work/92fa1b91071cafc3/SampleiOSProject/SampleiOSProject, /Users/arunsanthanam/buildAgent/work/92fa1b91071cafc3/SampleiOSProject/SampleiOSProjectTests
21:53:22.327 INFO - Source encoding: UTF-8, default locale: en_US
21:53:22.327 INFO - Index files
21:53:22.874 INFO - 18 files indexed
21:53:28.124 INFO - Quality profile for objc: OCLint
21:53:28.189 INFO - Sensor Quality gate loader...
21:53:28.189 INFO - Sensor Quality gate loader done: 0 ms
21:53:28.189 INFO - Sensor QProfileSensor...
21:53:28.294 INFO - Sensor QProfileSensor done: 105 ms
21:53:28.294 INFO - Sensor ObjectiveCSquidSensor...
21:53:28.503 INFO - Sensor ObjectiveCSquidSensor done: 209 ms
21:53:28.503 INFO - Sensor Objective-C SurefireSensor...
21:53:28.503 INFO - parsing sonar-reports
21:53:28.658 INFO - Sensor Objective-C SurefireSensor done: 155 ms
21:53:28.658 INFO - Sensor org.sonar.plugins.objectivec_dca.coverage.CoberturaSensor@37b3e1c9...
21:53:28.672 INFO - Processing coverage report /Users/arunsanthanam/buildAgent/work/92fa1b91071cafc3/SampleiOSProject/sonar-reports/coverage-SampleiOSProject.xml
21:53:30.519 INFO - Sensor org.sonar.plugins.objectivec_dca.coverage.CoberturaSensor@37b3e1c done: 1861 ms
21:53:30.519 INFO - Sensor org.sonar.plugins.objectivec_dca.violations.OCLintSensor@2ac6fb1...
21:53:30.519 INFO - Processing OCLint report /Users/arunsanthanam/buildAgent/work/92fa1b91071cafc3/SampleiOSProject/sonar-reports/oclint.xml
21:53:30.552 ERROR - Error while parsing XML stream.
com.ctc.wstx.exc.WstxParsingException: Unexpected close tag ; expected .
at [row,col {unknown-source}]: [80,5]
at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:580) ~[woodstox-core-lgpl-4.0.4.jar:4.0.4]
at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:453) ~[woodstox-core-lgpl-4.0.4.jar:4.0.4]
at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:438) ~[woodstox-core-lgpl-4.0.4.jar:4.0.4]
at com.ctc.wstx.sr.BasicStreamReader.reportWrongEndElem(BasicStreamReader.java:3234) ~[woodstox-core-lgpl-4.0.4.jar:4.0.4]
at com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3161) ~[woodstox-core-lgpl-4.0.4.jar:4.0.4]
at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2778) ~[woodstox-core-lgpl-4.0.4.jar:4.0.4]
at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1054) ~[woodstox-core-lgpl-4.0.4.jar:4.0.4]
at org.codehaus.staxmate.in.SMHierarchicCursor.getNext(SMHierarchicCursor.java:80) ~[staxmate-2.0.0.jar:na]
at org.sonar.plugins.objectivec_dca.violations.OCLintXMLStreamHandler.collectFileViolations(OCLintXMLStreamHandler.java:83) ~[sonar-objective-c-plugin-dca-0.4.jar:na]
at org.sonar.plugins.objectivec_dca.violations.OCLintXMLStreamHandler.collectViolationsFor(OCLintXMLStreamHandler.java:69) ~[sonar-objective-c-plugin-dca-0.4.jar:na]
at org.sonar.plugins.objectivec_dca.violations.OCLintXMLStreamHandler.stream(OCLintXMLStreamHandler.java:56) ~[sonar-objective-c-plugin-dca-0.4.jar:na]
at org.sonar.api.utils.StaxParser.parse(StaxParser.java:109) ~[sonar-plugin-api-4.2.jar:na]
at org.sonar.api.utils.StaxParser.parse(StaxParser.java:89) ~[sonar-plugin-api-4.2.jar:na]
at org.sonar.plugins.objectivec_dca.violations.OCLintParser.parseReport(OCLintParser.java:65) [sonar-objective-c-plugin-dca-0.4.jar:na]
at org.sonar.plugins.objectivec_dca.violations.OCLintParser.parseReport(OCLintParser.java:50) [sonar-objective-c-plugin-dca-0.4.jar:na]
at org.sonar.plugins.objectivec_dca.violations.OCLintSensor.parseReportIn(OCLintSensor.java:74) [sonar-objective-c-plugin-dca-0.4.jar:na]
at org.sonar.plugins.objectivec_dca.violations.OCLintSensor.analyse(OCLintSensor.java:56) [sonar-objective-c-plugin-dca-0.4.jar:na]
at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:79) [sonar-batch-4.2.jar:na]
at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:70) [sonar-batch-4.2.jar:na]
at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:134) [sonar-batch-4.2.jar:na]
at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:186) [sonar-batch-4.2.jar:na]
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92) [sonar-plugin-api-4.2.jar:na]
at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77) [sonar-plugin-api-4.2.jar:na]
at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:199) [sonar-batch-4.2.jar:na]
at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:194) [sonar-batch-4.2.jar:na]
at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:187) [sonar-batch-4.2.jar:na]
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92) [sonar-plugin-api-4.2.jar:na]
at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77) [sonar-plugin-api-4.2.jar:na]
at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:56) [sonar-batch-4.2.jar:na]
at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:44) [sonar-batch-4.2.jar:na]
at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:82) [sonar-batch-4.2.jar:na]
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92) [sonar-plugin-api-4.2.jar:na]
at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77) [sonar-plugin-api-4.2.jar:na]
at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:144) [sonar-batch-4.2.jar:na]
at org.sonar.batch.bootstrap.BootstrapContainer.doAfterStart(BootstrapContainer.java:132) [sonar-batch-4.2.jar:na]
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92) [sonar-plugin-api-4.2.jar:na]
at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77) [sonar-plugin-api-4.2.jar:na]
at org.sonar.batch.bootstrapper.Batch.startBatch(Batch.java:92) [sonar-batch-4.2.jar:na]
at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:74) [sonar-batch-4.2.jar:na]
at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:45) [sonar-runner-batch3301625115031993235.jar:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_65]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_65]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_65]
at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_65]
at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87) [sonar-runner-dist-2.3.jar:na]
at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75) [sonar-runner-dist-2.3.jar:na]
at java.security.AccessController.doPrivileged(Native Method) [na:1.6.0_65]
at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69) [sonar-runner-dist-2.3.jar:na]
at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50) [sonar-runner-dist-2.3.jar:na]
at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102) [sonar-runner-dist-2.3.jar:na]
at org.sonar.runner.api.Runner.execute(Runner.java:90) [sonar-runner-dist-2.3.jar:na]
at org.sonar.runner.Main.executeTask(Main.java:70) [sonar-runner-dist-2.3.jar:na]
at org.sonar.runner.Main.execute(Main.java:59) [sonar-runner-dist-2.3.jar:na]
at org.sonar.runner.Main.main(Main.java:41) [sonar-runner-dist-2.3.jar:na]
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 31.473s
Final Memory: 5M/89M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: The rule 'OCLint:avoid private static members' does not exist.
ERROR: 
ERROR: To see the full stack trace of the errors, re-run SonarQube Runner with the -e switch.
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
Rajasekaran-MacBook-Pro-4:SampleiOSProject arunsanthanam$ sonar-runner

**Comment by cyrilpicat** [comment]
Fixed in 0.4.0, rules have been updated to the latest oclint version.
